Controllers/BrowserController.cs

namespace EEBUS.Controllers
{
    using EEBUS.Enums;
    using EEBUS.Models;
    using Microsoft.AspNetCore.Mvc;
    using Newtonsoft.Json;
    using System;
    using System.Net;
    using System.Net.Security;
    using System.Net.WebSockets;
    using System.Security.Cryptography.X509Certificates;
    using System.Text;
    using System.Threading;
    using System.Threading.Tasks;

    public class BrowserController : Controller
    {
        private readonly MDNSClient _mDNSClient;
        private static ClientWebSocket _wsClient;
        private ServerNode _model = new ServerNode();

        public BrowserController(MDNSClient mDNSClient)
        {
            _mDNSClient = mDNSClient;
        }

        public IActionResult Index()
        {
            try
            {
                return View("Index", _mDNSClient.getEEBUSNodes());
            }
            catch (Exception ex)
            {
                _model.Error = "Error: " + ex.Message;
                return View("Index", _model);
            }
        }

        private bool ValidateServerCert(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
        {
            // extract SKI
            foreach (X509Extension extension in ((X509Certificate2)certificate).Extensions)
            {
                if (extension.Oid.FriendlyName == "Subject Key Identifier")
                {
                    X509SubjectKeyIdentifierExtension ext = (X509SubjectKeyIdentifierExtension)extension;
                    _model.SKI = ext.SubjectKeyIdentifier;

                    // add spaces every 4 hex digits (EEBUS requirement)
                    for (int i = 4; i < _model.SKI.Length; i += 4)
                    {
                        _model.SKI = _model.SKI.Insert(i, " ");
                        i++;
                    }

                    break;
                }
            }

            return true;
        }

        [HttpPost]
        public async Task<IActionResult> Connect()
        {
            try
            {
                foreach (string key in Request.Form.Keys)
                {
                    if (key.Contains("EEBUS:"))
                    {
                        string[] parts = key.Split(' ');
                        _model.Name = parts[1];
                        _model.Id = parts[2];
                        _model.Url = parts[3];
                        break;
                    }
                }

                _wsClient = new ClientWebSocket();
                _wsClient.Options.AddSubProtocol("ship");
                _wsClient.Options.RemoteCertificateValidationCallback = ValidateServerCert;
                X509Certificate2 cert = CertificateGenerator.GenerateCert(Dns.GetHostName());
                _wsClient.Options.ClientCertificates.Add(cert);
                await _wsClient.ConnectAsync(new Uri("wss://" + _model.Url), CancellationToken.None).ConfigureAwait(false);
                
                return View("Accept", _model);
            }
            catch (Exception ex)
            {
                _model.Error = "Error: " + ex.Message;
                return View("Index", new ServerNode[] { _model });
            }
        }

        [HttpPost]
        public async Task<IActionResult> Accept()
        {
            try
            {
                foreach (string key in Request.Form.Keys)
                {
                    if (key.Contains("EEBUS:"))
                    {
                        string[] parts = key.Split(' ');
                        _model.Name = parts[1];
                        _model.Id = parts[2];
                        _model.Url = parts[3];
                        break;
                    }
                }

                if (_wsClient.State == WebSocketState.Open)
                {
                    if (!await InitPhase().ConfigureAwait(false))
                    {
                        return await Disconnect().ConfigureAwait(false);
                    }

                    if (!await HelloPhase().ConfigureAwait(false))
                    {
                        return await Disconnect().ConfigureAwait(false);
                    }

                    if (!await HandshakePhase().ConfigureAwait(false))
                    {
                        return await Disconnect().ConfigureAwait(false);
                    }

                    return View("Connected", _model);
                }
                else
                {
                    return await Disconnect().ConfigureAwait(false);
                }
            }
            catch (Exception ex)
            {
                return await Disconnect(ex.Message).ConfigureAwait(false);
            }
        }

        [HttpPost]
        public async Task<IActionResult> SendTestData()
        {
            return await SendData("SPINE test data").ConfigureAwait(false);
        }

        [HttpPost]
        public async Task<IActionResult> SendSPINEData(SPINE spine)
        {
            foreach (string key in Request.Form.Keys)
            {
                if (key.Contains("EEBUS:"))
                {
                    string[] parts = key.Split(' ');
                    _model.Name = parts[1];
                    _model.Id = parts[2];
                    _model.Url = parts[3];
                    break;
                }
            }

            return await SendData(spine.GenerateDatagram(_model.Url)).ConfigureAwait(false);
        }


        private async Task<IActionResult> SendData(object payload)
        {
            try
            {
                foreach (string key in Request.Form.Keys)
                {
                    if (key.Contains("EEBUS:"))
                    {
                        string[] parts = key.Split(' ');
                        _model.Name = parts[1];
                        _model.Id = parts[2];
                        _model.Url = parts[3];
                        break;
                    }
                }

                if (_wsClient.State == WebSocketState.Open)
                {
                    // send data message
                    SHIPDataMessage dataMessage = new SHIPDataMessage();
                    dataMessage.data.header = new HeaderType();
                    dataMessage.data.header.protocolId = "spine";
                    dataMessage.data.payload = payload;
                    
                    byte[] dataMessageSerialized = Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(dataMessage));
                    byte[] dataMessageBuffer = new byte[dataMessageSerialized.Length + 1];

                    dataMessageBuffer[0] = SHIPMessageType.DATA;
                    Buffer.BlockCopy(dataMessageSerialized, 0, dataMessageBuffer, 1, dataMessageSerialized.Length);

                    await _wsClient.SendAsync(dataMessageBuffer, WebSocketMessageType.Binary, true, new CancellationTokenSource(SHIPMessageTimeout.CMI_TIMEOUT).Token).ConfigureAwait(false);

                    // wait for data response message from server
                    byte[] dataResponse = new byte[1024];
                    WebSocketReceiveResult result = await _wsClient.ReceiveAsync(dataResponse, new CancellationTokenSource(SHIPMessageTimeout.CMI_TIMEOUT).Token).ConfigureAwait(false);
                    if (result.MessageType == WebSocketMessageType.Close)
                    {
                        return await Disconnect().ConfigureAwait(false);
                    }

                    if ((result.Count < 2) || (dataResponse[0] != SHIPMessageType.DATA))
                    {
                        throw new Exception("Data message expected!");
                    }

                    byte[] dataResponseMessageBuffer = new byte[result.Count - 1];
                    Buffer.BlockCopy(dataResponse, 1, dataResponseMessageBuffer, 0, result.Count - 1);

                    var settings = new JsonSerializerSettings
                    {
                        NullValueHandling = NullValueHandling.Include,
                        MissingMemberHandling = MissingMemberHandling.Error
                    };

                    SHIPDataMessage dataMessageReceived = JsonConvert.DeserializeObject<SHIPDataMessage>(Encoding.UTF8.GetString(dataResponseMessageBuffer), settings);
                    if ((dataMessageReceived == null) || (dataMessageReceived.data == null) || (dataMessageReceived.data.payload == null))
                    {
                        throw new Exception("Data message parsing failed!");
                    }
                    else
                    {
                        _model.LatestDataReceived = dataMessageReceived.data.payload.ToString();
                    }

                    return View("Connected", _model);
                }
                else
                {
                    return await Disconnect().ConfigureAwait(false);
                }
            }
            catch (Exception ex)
            {
                return await Disconnect(ex.Message).ConfigureAwait(false);
            }
        }

        private async Task<bool> InitPhase()
        {
            // send init request message
            byte[] initRequest = new byte[2];
            initRequest[0] = SHIPMessageType.INIT;
            initRequest[1] = SHIPMessageValue.CMI_HEAD;

            await _wsClient.SendAsync(initRequest, WebSocketMessageType.Binary, true, new CancellationTokenSource(SHIPMessageTimeout.CMI_TIMEOUT).Token).ConfigureAwait(false);

            // wait for init response message from server
            byte[] initResponse = new byte[2];

Views/Browser/Accept.cshtml
@using EEBUS.Models

@model ServerNode

@{
    ViewData["Title"] = "Browse EEBUS Servers";
}

<h1>@ViewData["Title"]</h1>

 <p>
    <h3>Connect to @Model.Name?</h3>
 </p>

<div class="container-fluid browser_connect_container">
    @if (Model.Error != null)
    {
        <div>
            @Model.Error
        </div>
    }
    else
    {
        <div>
            Subject Key Identifier: @Model.SKI
        </div>
        <div>
            <p/>
            <form method="post" enctype="multipart/form-data" asp-controller="Browser" asp-action="Accept">
                <input name="EEBUS: @Model.Name @Model.Id @Model.Url" class="btn btn-primary" type="submit" value="Accept">
            </form>
            <p/>
            <form method="post" enctype="multipart/form-data" asp-controller="Browser" asp-action="Disconnect">
                <input class="btn btn-primary" type="submit" value="Cancel">
            </form>
        </div>
    }
</div>

Views/Browser/Connected.cshtml
@using EEBUS.Models

@model ServerNode

@{
    ViewData["Title"] = "Browse EEBUS Servers";
}

<h1>@ViewData["Title"]</h1>

 <p>
    <h3>Connected to @Model.Name</h3>
 </p>

<div class="container-fluid browser_connect_container">
    @if (Model.Error != null)
    {
        <div>
            @Model.Error
        </div>
    }
    else
    {
        <div>
            <p/>
            <form method="post" enctype="multipart/form-data" asp-controller="Browser" asp-action="SendTestData">
                <input name="EEBUS: @Model.Name @Model.Id @Model.Url" class="btn btn-primary" type="submit" value="Send Test Data">
            </form>
            <p/>
            <form method="post" enctype="multipart/form-data" asp-controller="Browser" asp-action="SendSPINEData">
                <input name="EEBUS: @Model.Name @Model.Id @Model.Url" class="btn btn-primary" type="submit" value="Send SPINE Data">
            </form>
            <p/>
            Last Data Message Received: @Model.LatestDataReceived
            <p/>
            <form method="post" enctype="multipart/form-data" asp-controller="Browser" asp-action="Disconnect">
                <input class="btn btn-primary" type="submit" value="Disconnect">
            </form>
        </div>
    }
</div>

Views/Browser/Index.cshtml
@using EEBUS.Models

@model ServerNode[]

@{
    ViewData["Title"] = "Browse EEBUS Servers";
}

<h1>@ViewData["Title"]</h1>

 <p>
    <h3>List of Currently discovered EEBUS nodes:</h3>
 </p>

<div class="container-fluid browser_connect_container">
    <ul>
        @foreach (var node in Model) 
        {
            @if (node.Error != null)
            {
                @node.Error
            }
            else
            {
                <li>
                    @node.Name<br/>
                    @node.Id<br/>
                    @node.Url<br/>
                    <p/>
                    <form method="post" enctype="multipart/form-data" asp-controller="Browser" asp-action="Connect">
                        <input name="EEBUS: @node.Name @node.Id @node.Url" class="btn btn-primary" type="submit" value="Connect">
                    </form>
                    <hr />
                </li>
            }
        }
    </ul>
</div>